from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.4.1")


#containerized: "docker://ghcr.io/ht-diva/pqtl_pipeline:d0d53c1"

configfile: "config/config.yaml"
config_copy="config/config.yaml"


include: "rules/common.smk"
include: "rules/return_config.smk"
include: "rules/query_gwas.smk"
include: "rules/query_pwas.smk"
include: "rules/coloc_abf.smk"
include: "rules/combine_results.smk"


rule all:
    input:
        ws_path("config/config_used.yaml"),
        #expand(ws_path("tmp/pwas/{locuseq}_sumstat.csv.gz"), locuseq = data.locuseq),
        #expand(ws_path("tmp/gwas/{locuseq}/{locuseq}.sentinel"), locuseq = data.locuseq),
        #expand(ws_path("tmp/coloc/{locuseq}_coloc_results.csv"), locuseq = data.locuseq),
        ws_path("combined_coloc_results.tsv"),
