from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.4.1")


#containerized: "docker://ghcr.io/ht-diva/pqtl_pipeline:d0d53c1"

#configfile: "config/config.yaml"
#config_copy="config/config.yaml"


include: "rules/common.smk"
#include: "rules/return_config.smk"
include: "rules/query_gwas.smk"


rule all:
    input:
        #expand(ws_path("tmp/{locuseq}_snps.list"), locuseq = data.locuseq),
        ws_path("susierss/collected_credible_sets.tsv"),