executor: slurm
jobs: 250
software-deployment-method:
   - conda
   - apptainer
retries: 3
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 4
latency-wait: 60
keep-going: True
rerun-incomplete: False
printshellcmds: True
scheduler: ilp


default-resources:
    slurm_partition: cpuq
    mem_mb: attempt * 256
    threads: 1
    runtime: attempt * 5
set-threads:
    harmonize_sumstats: *cores
    bgzip_tabix: *cores
set-resources:
    query_pwas:
        mem_mb: 1024 + attempt * 1024
    query_gwas:
        mem_mb: 2048 + attempt * 1024
    run_coloc:
        mem_mb: 1024 + attempt * 2048
    combine_results:
        mem_mb: 4000 + attempt * 2048